(function(WINDOW){
	var ARRAY = Array;

	var	TOLOWERCASE = 'toLowerCase',
		TOUPPERCASE = 'toUpperCase',
		CONSOLE = 'CONSOLE'[TOLOWERCASE](),
		SHOUT = 'SHOUT'[TOLOWERCASE](),
		LENGTH = 'LENGTH'[TOLOWERCASE](),
		STRING = 'STRING'[TOLOWERCASE](),
		PROTOTYPE = 'PROTOTYPE'[TOLOWERCASE](),
		WARN = 'WARN'[TOLOWERCASE](),
		LOG = 'LOG'[TOLOWERCASE](),
		APPLY = 'APPLY'[TOLOWERCASE](),
		SLICE = 'SLICE'[TOLOWERCASE](),
		JOIN = 'JOIN'[TOLOWERCASE](),
		CALL = 'CALL'[TOLOWERCASE]();

	//	IF THERE'S NO CONSOLE AROUND TO HEAR IT, DOES SHOUTING MAKE A SOUND?!
	// if(WINDOW[CONSOLE] || !WINDOW[CONSOLE][SHOUT]){
		//	ALIAS TO SOMETHING EVEN MORE HARDCORE!
		WINDOW[CONSOLE][SHOUT] = WINDOW[CONSOLE].SHOUT = function(){
			var ARGS = ARRAY[PROTOTYPE][SLICE][CALL](arguments),
				MAGNITUDE = 1;

			//	WE SHOUT LOUDER WITH EACH ARGUMENT!
			var A, ARGSLENGTH = ARGS[LENGTH];
			for(A = 0; A < ARGSLENGTH; A++){
				if(typeof ARGS[A] === STRING){
					//	SCREAM THAT SHIT AT THE TOP OF YOUR LUNGS!
					ARGS[A] = ARGS[A][TOUPPERCASE]() + ARRAY(++MAGNITUDE)[JOIN]('!');
				}
			}

			//	USE WARN IF AVAILABLE, FOR SOME EXTRA VOLUME!
			WINDOW[CONSOLE][(WINDOW[CONSOLE][WARN]) ? WARN : LOG][APPLY](WINDOW[CONSOLE], ARGS);
		};
	// }
})(window);
